<?php

namespace Database\Seeders;

use App\Enums\SupplyTypeEnum;
use App\Models\Inventory;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medicines = [
            [
                'item_name' => 'Acide Folique 5mg',
                'category' => 'Tablet',
                'barcode' => 'NE0110',
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 500,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 3000,
                'minimum_stock' => 1000,
                'unit_price' => 0.00,
                'selling_price' => 0.04,
                'expiry_date' => '2028-08-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Albendazole 400mg',
                'category' => 'Tablet',
                'barcode' => 'NE0113',
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 10000,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 10,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 1.50,
                'expiry_date' => '2026-02-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Albumin',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Bottle',
                'total_per_box' => 5,
                'minimum_stock' => 2,
                'unit_price' => 0.00,
                'selling_price' => 70.00,
                'expiry_date' => '2026-03-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Alphachymoral (1box=30tb)',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 30,
                'minimum_stock' => 10,
                'unit_price' => 0.00,
                'selling_price' => 0.08,
                'expiry_date' => '2026-08-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Amoxicilline500mg',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 100,
                'minimum_stock' => 20,
                'unit_price' => 0.00,
                'selling_price' => 0.24,
                'expiry_date' => '2026-03-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Aspririn 81mg',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 500,
                'minimum_stock' => 100,
                'unit_price' => 0.00,
                'selling_price' => 0.04,
                'expiry_date' => '2027-09-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Azitro 500mg(1box=3c)',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 100,
                'minimum_stock' => 20,
                'unit_price' => 0.00,
                'selling_price' => 1.50,
                'expiry_date' => '2027-04-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Cefixim 400mg (1box=5tb)',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 20,
                'minimum_stock' => 10,
                'unit_price' => 0.00,
                'selling_price' => 2.00,
                'expiry_date' => '2027-09-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Ceftriaxone 1g(1box=10)',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Bottle',
                'total_per_box' => 10,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 5.00,
                'expiry_date' => '2027-12-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Chlorpheniramine meleate 4mg(1box=100tb)',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 10,
                'minimum_stock' => 10,
                'unit_price' => 0.00,
                'selling_price' => 0.10,
                'expiry_date' => '2025-12-12',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Clindamycine 300mg(1box=100tb)',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 100,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 1.00,
                'expiry_date' => '2026-09-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Colpotropine 10mg (1box=20tb)',
                'category' => 'Vaginal Insert',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 10,
                'minimum_stock' => 10,
                'unit_price' => 0.00,
                'selling_price' => 1.00,
                'expiry_date' => '2026-03-27',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Cytotec 200mg',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 20,
                'minimum_stock' => 14,
                'unit_price' => 0.00,
                'selling_price' => 2.20,
                'expiry_date' => '2027-07-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'D5%S 500ml (1box=20fl)',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Bottle',
                'total_per_box' => 20,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 10.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Dexamethasone injection',
                'category' => 'Ampoul',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Ampoul',
                'total_per_box' => 10,
                'minimum_stock' => 3,
                'unit_price' => 0.00,
                'selling_price' => 1.00,
                'expiry_date' => '2026-01-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Bepantan inj',
                'category' => 'Ampoul',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Ampoul',
                'total_per_box' => 10,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 2.00,
                'expiry_date' => '2026-07-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Besilan inj',
                'category' => 'Ampoul',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Ampoul',
                'total_per_box' => 15,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 2.00,
                'expiry_date' => '2025-03-27',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Becozym inj',
                'category' => 'Ampoul',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Ampoul',
                'total_per_box' => 20,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 3.00,
                'expiry_date' => '2025-09-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Doxycycline 100mg (1box=100tb)',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 100,
                'minimum_stock' => 20,
                'unit_price' => 0.00,
                'selling_price' => 0.20,
                'expiry_date' => '2028-01-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Duphastan(1box=20tb)',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 2000,
                'minimum_stock' => 100,
                'unit_price' => 0.00,
                'selling_price' => 1.00,
                'expiry_date' => '2027-08-27',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Erythromycin 500',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 50,
                'minimum_stock' => 10,
                'unit_price' => 0.00,
                'selling_price' => 0.32,
                'expiry_date' => '2026-03-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Etocox (1box=20tb)90mg',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 30,
                'minimum_stock' => 3,
                'unit_price' => 0.00,
                'selling_price' => 1.50,
                'expiry_date' => '2026-04-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Flagyl pessery (1box=10p)',
                'category' => 'Vaginal Insert',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 10,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 1.00,
                'expiry_date' => '2027-01-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Fluconazole 200mg',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 50,
                'minimum_stock' => 10,
                'unit_price' => 0.00,
                'selling_price' => 0.50,
                'expiry_date' => '2026-03-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Glocuse(1box=10amp) 50%',
                'category' => 'Ampoul',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Ampoul',
                'total_per_box' => 10,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 2.00,
                'expiry_date' => '2026-06-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Larose (vit C inj 1box/6amp)',
                'category' => 'Ampoul',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Ampoul',
                'total_per_box' => 2,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 3.60,
                'expiry_date' => '2027-09-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'LR 500(ml)',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Bottle',
                'total_per_box' => 5,
                'minimum_stock' => 5,
                'unit_price' => 0.00,
                'selling_price' => 10.00,
                'expiry_date' => '2026-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Mavelon 21',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'គ្រាប់',
                'total_per_box' => 5,
                'minimum_stock' => 2,
                'unit_price' => 0.00,
                'selling_price' => 10.00,
                'expiry_date' => '2026-06-25',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Medabon box',
                'category' => 'Tablet',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'box',
                'total_per_box' => 2,
                'minimum_stock' => 1,
                'unit_price' => 0.00,
                'selling_price' => 20.00,
                'expiry_date' => '2025-07-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Metronidazol 100ml injection',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::RX_MEDICINE,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'Bottle',
                'total_per_box' => 5,
                'minimum_stock' => 2,
                'unit_price' => 0.00,
                'selling_price' => 5.00,
                'expiry_date' => '2027-01-24',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Alcohol (hand wash)',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::CLEANING_SUPPLY,
                'quantity' => 0,
                'unit' => 'bottle',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Alcohol Pad (100 Pieces/pack)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Bed Pan (កន្ថោរគ្រែ)',
                'category' => 'Equipment',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'piece',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Betadine Gyneco / Chiv Tong',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICATION,
                'quantity' => 0,
                'unit' => 'bottle',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Betadine Scurb/Chiv Tong 200ml',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICATION,
                'quantity' => 0,
                'unit' => 'bottle',
                'dose_unit' => null,
                'total_per_box' => 4,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Blood Pressure Papper roll',
                'category' => 'Roll',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::OFFICE_SUPPLY,
                'quantity' => 0,
                'unit' => 'roll',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Client Bedsheet for OR(ដុំ)',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'roll',
                'dose_unit' => null,
                'total_per_box' => 10,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Cotton 500g',
                'category' => 'Roll',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'roll',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Compress Roll ( 1 kg)',
                'category' => 'Roll',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'roll',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Condom ( 1 box= 24pcs)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Disaposable infusion(ទ្រុស)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 20,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Drape with hole (80*120)',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'roll',
                'dose_unit' => null,
                'total_per_box' => 100,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Echo Jelly',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'bottle',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Echo Paper Roll- Sony',
                'category' => 'Roll',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'roll',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Estetice set',
                'category' => 'Set',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Extention Tube- Nipro',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 50,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Face Mask',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Forcep Clipper(+ក្រណាត់រំ​guid prob)',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Glove non sterile (M)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Glove non sterile (S)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 10,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Glove sterile Gammex PF # 7(box)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 4,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'IV Catheter 20 (HEALFLON)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'IV Cathetor 22',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'IV Cathetor 24',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'IV Cathetor 24x3/4(អត់ស្លាប)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'KY Jelly',
                'category' => 'Tube',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'tube',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Medication Bag(white)',
                'category' => 'Bag',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'kg',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Medication Bag(white)(small)',
                'category' => 'Bag',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'kg',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'MVA(ប្រដាប់កោសស្បូន)',
                'category' => 'Set',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Needle NO. 18x1 1/2',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Needle NO. 24x1 1/4 (0.55x25 mm)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'O2 Tube',
                'category' => 'Pack',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'pack',
                'dose_unit' => null,
                'total_per_box' => 10,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Safty Box',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'unit',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Scavien No. 24 X 3/4',
                'category' => 'Pack',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'pack',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Set ET',
                'category' => 'Set',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 10,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Set Gyn',
                'category' => 'Set',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 10,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'SET MVA',
                'category' => 'Set',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Set OPU',
                'category' => 'Set',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Small Sugery',
                'category' => 'Set',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Sond Urine',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'unit',
                'dose_unit' => null,
                'total_per_box' => 10,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Steranios 2%',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICATION,
                'quantity' => 0,
                'unit' => 'bottle',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Stericlin -tap scot for steril(ស្គុតស្តេរីល)',
                'category' => 'Roll',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'roll',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Sterile Glove 6​ 1/2(Powder free)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Sterile Glove 7(Powder free)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Sterile Glove 7 1/2 (Powder free)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Surfa Safe( ANIOS) BIG',
                'category' => 'Bottle',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::CLEANING_SUPPLY,
                'quantity' => 0,
                'unit' => 'bottle',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Surfgical Blade(កូនកាំបិតវះ)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Surgical Cap',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'unit',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Syring 10cc',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Syring 1cc',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Syring 20cc',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Syring 3cc',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Syring 5cc',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Trape (Green) (OPU+FET)',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'unit',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Trape (ត្រូយចេក) (GYN)',
                'category' => 'Bag',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'bag',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Plateur( HERO)(បង់បិទដំបៅ)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 5,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Urinalysis for ANC',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Vigril (Poly 1/0)',
                'category' => 'Pack',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'pack',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Vigril (Poly 2/0)',
                'category' => 'Pack',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'pack',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Vigril (Poly 3/0)',
                'category' => 'Pack',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'pack',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Vigril (Poly 4/0) (1box=12pcs)',
                'category' => 'Pack',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'pack',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Zip Bag 10x15',
                'category' => 'Bag',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'kg',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Zip Bag 15x23',
                'category' => 'Bag',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'kg',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Zip Bag 18x28',
                'category' => 'Bag',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'kg',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Zip Bag 8x12',
                'category' => 'Bag',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'kg',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Plain tube (green blood tube)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Plain tube (purple blood tube)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Plain tube (red blood tube)',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Ambulbag(Mask 3)',
                'category' => 'Set',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Postpartum Balloon',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Thin-prep cans',
                'category' => 'Can',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'can',
                'dose_unit' => null,
                'total_per_box' => 10,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'ExEm Faom Kit(box)+ syring',
                'category' => 'Kit',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'kit',
                'dose_unit' => null,
                'total_per_box' => 4,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'Pregnancy Test',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'unit',
                'dose_unit' => null,
                'total_per_box' => 20,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'សំលីអនាម័យ',
                'category' => 'Roll',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'roll',
                'dose_unit' => null,
                'total_per_box' => 2,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'ស្តេតូស្កុប',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'unit',
                'dose_unit' => null,
                'total_per_box' => 1,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'សំលីតំបារ',
                'category' => 'Material',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::MEDICAL_EQUIPMENT,
                'quantity' => 0,
                'unit' => 'unit',
                'dose_unit' => null,
                'total_per_box' => 3,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
            [
                'item_name' => 'LH Test',
                'category' => 'Box',
                'barcode' => null,
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => null,
                'total_per_box' => 10,
                'minimum_stock' => 0,
                'unit_price' => 0.00,
                'selling_price' => 0.00,
                'expiry_date' => '2025-12-26',
                'alert_days' => 90,
            ],
        ];

        foreach ($medicines as $medicine) {
            Inventory::create($medicine);
        }
    }
}
