<?php

namespace Database\Seeders;

use App\Enums\SupplyTypeEnum;
use App\Models\Inventory;
use Illuminate\Database\Seeder;

class IvfInventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Plastic Ware Stock - AFC Location
        $afcPlasticWare = [
            [
                'item_name' => '4 wells Dish',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 120,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 20,
                'unit_price' => 220.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Central well Dish (CT)',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 500,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 50,
                'unit_price' => 393.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Petri Dish (ICSI Dish)',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 500,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 50,
                'unit_price' => 547.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Small Round Plate',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 500,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 50,
                'unit_price' => 135.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Big Round Plate',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 500,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 50,
                'unit_price' => 347.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Conical Tube',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 500,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 50,
                'unit_price' => 153.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Easy Flask 25 vic',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 200,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 20,
                'unit_price' => 141.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '5 ml Tube (small Round butt)',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 500,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 50,
                'unit_price' => 197.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '14 ml Tube (Big round butt)',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 500,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 50,
                'unit_price' => 235.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '1 ml serological pipette',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 250,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 25,
                'unit_price' => 69.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '5 ml serological pipette',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 39.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '10 ml serological pipette',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 44.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Eppendorf micro pipette',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 52.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '10 micro pipette tip (sterile)',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 0.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
                'notes' => 'Out of stock',
            ],
            [
                'item_name' => '1000 microlite pipette tip',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'rack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 9.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Short Pipette Glass',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 250,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 25,
                'unit_price' => 198.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Long Pipette Glass',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 250,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 25,
                'unit_price' => 157.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '1 ml Nipro Syringe/Tuberculin',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 8.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '3 ml Nipro Syringe',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 5.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '5 ml Nipro Syringe',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 0.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
                'notes' => 'Unknown quantity',
            ],
            [
                'item_name' => 'ICSI Needle',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 10,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 2,
                'unit_price' => 314.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Holding Needle',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 10,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 2,
                'unit_price' => 283.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Biopsy Needle',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 10,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 2,
                'unit_price' => 314.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Globet',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 10,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 2,
                'unit_price' => 8.50,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Cryo Aluminium Cane',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 50,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 5,
                'unit_price' => 65.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Cryo Vial 1.8 ml',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 50,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 5,
                'unit_price' => 18.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Cryotech Straw',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 10,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 2,
                'unit_price' => 267.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'K-JET7019 ET catheter',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'pcs',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 44.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Gynetic IUI Catheter',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 15,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 3,
                'unit_price' => 251.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '17G Single Lumen/Wallace',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 10,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 2,
                'unit_price' => 503.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Double lumen/COOK',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'pcs',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 59.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Stripper Tip 145',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 10,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 2,
                'unit_price' => 63.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Tube load',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 0.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
                'notes' => 'Free',
            ],
            [
                'item_name' => 'PBS',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'pack',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 0.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
                'notes' => 'Free',
            ],
            [
                'item_name' => 'Sterile Water',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 1,
                'unit_price' => 1.80,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Minisart syringe filter',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 50,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 5,
                'unit_price' => 94.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Sterile Bottle for BT',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'bottle',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 94.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Len Paper',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 100.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => '3M Parafilm',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 31.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'PH paper (Sperm)',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 25.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Sperm Container/Millionant',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 300,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 30,
                'unit_price' => 69.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Sterile Guaze Pad',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'box',
                'dose_unit' => 'pcs',
                'minimum_stock' => 10,
                'unit_price' => 8.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Spare cork and cover for LAB30',
                'category' => 'Plastic Ware',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'pcs',
                'dose_unit' => 'pcs',
                'minimum_stock' => 1,
                'unit_price' => 168.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
        ];

        // Culture Medium Stock - AFC Location
        $afcCultureMedium = [
            [
                'item_name' => 'Sage 1 step',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 60,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 6,
                'unit_price' => 311.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Irvine-CSCM',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 20,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 2,
                'unit_price' => 226.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Sperm preparation',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 60,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 6,
                'unit_price' => 141.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Flushing Medium',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 10,
                'unit_price' => 59.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Aspiration Medium',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 100,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 10,
                'unit_price' => 44.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Hyaluronidase',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 10,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 1,
                'unit_price' => 63.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'PVP 10%',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 1,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 1,
                'unit_price' => 63.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Vitrification (Freezing)/KITAZATO',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'kit',
                'minimum_stock' => 1,
                'unit_price' => 189.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Thawing/KITAZATO',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'box',
                'dose_unit' => 'kit',
                'minimum_stock' => 1,
                'unit_price' => 141.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Sperm Freezing',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 20,
                'unit' => 'box',
                'dose_unit' => 'kit',
                'minimum_stock' => 2,
                'unit_price' => 63.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Sil Selection Set',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 0,
                'unit' => 'set',
                'dose_unit' => 'set',
                'minimum_stock' => 1,
                'unit_price' => 440.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
            [
                'item_name' => 'Lite Oil',
                'category' => 'Culture Medium',
                'type_of_supply' => SupplyTypeEnum::LAB_SUPPLY,
                'quantity' => 500,
                'unit' => 'bottle',
                'dose_unit' => 'ml',
                'minimum_stock' => 50,
                'unit_price' => 313.00,
                'location' => 'AFC',
                'supplier' => 'AFC IVF',
                'alert_days' => 30,
            ],
        ];

        // Insert AFC Plastic Ware
        foreach ($afcPlasticWare as $item) {
            Inventory::create($item);
        }

        // Insert AFC Culture Medium
        foreach ($afcCultureMedium as $item) {
            Inventory::create($item);
        }

        // Note: Atchyut data would need to be added separately if quantities/prices differ
        // For now, only AFC data is being seeded as provided
    }
}
