<script setup lang="ts">
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useAuth } from '@/composables/useAuth';
import { formatDate, formatDateTime } from '@/lib/utils';
import AppLayout from '@/layouts/AppLayout.vue';
import PatientFilesTab from '@/pages/Patients/PatientFilesTab.vue';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, router, usePage } from '@inertiajs/vue3';
import { ArrowLeft, Edit, Printer, User, Calendar, ChevronRight, FlaskConical, Download, Eye } from 'lucide-vue-next';
import { ref, computed } from 'vue';
import { show as showPatientFile } from '@/routes/patient-files';

const page = usePage();
const flashError = computed(() => (page.props as any)?.flash?.error);
const formErrors = computed(() => (page.props as any)?.errors ?? {});

const expandedVisits = ref<Set<number>>(new Set());
const visitHistoryDate = ref('');
const clearVisitHistoryDate = () => {
    visitHistoryDate.value = '';
};

const medicineReportDate = ref('');
const clearMedicineReportDate = () => {
    medicineReportDate.value = '';
};
const filteredMedicineReport = computed(() => {
    const meds = (props.patient.medical_orders_data || [])
        .flatMap((order: any) => ((order.medications || []) as any[]).map((med: any) => ({
            id: order.id,
            date: order.ordered_at ? order.ordered_at.slice(0, 10) : '',
            ...med,
        })));
    if (!medicineReportDate.value) {
        return meds;
    }
    return meds.filter((med: any) => med.date === medicineReportDate.value);
});

const filteredVisitHistory = computed(() => {
    if (!visitHistoryDate.value) {
        return props.patient.visit_history || [];
    }
    return (props.patient.visit_history || []).filter(v => v.visit_date_time && v.visit_date_time.startsWith(visitHistoryDate.value));
});

// Lab Results tab reads from patient_files (type = lab_result) — the PDFs
// generated by the Lab Panel report forms (Hormone/SA/Semen Analysis/CBC/
// IUI/OPU/FET/Sperm Freezing) and the quick-entry endpoint. This mirrors the
// "Lab Files" grouping already used in PatientFilesTab.vue, since that is
// the data source that's actually kept up to date — MedicalOrderInventory's
// result_value/status fields are only ever written by the old single-value
// quick-entry flow and don't reflect results entered via the report forms.
const labResultGroups = computed(() => {
    const files = ((props.patient.patient_files || []) as Array<{
        id: number;
        type: string;
        medical_order_id?: number | null;
        created_at: string;
        file: { id: number; name: string; size: number; mime_type: string };
    }>)
        .filter((f) => f.type === 'lab_result')
        .sort((a, b) => (b.created_at || '').localeCompare(a.created_at || ''));

    const orderLookup = new Map((props.patient.medical_orders_data || []).map((o: any) => [o.id, o]));

    const groupsByKey: Record<string, { key: string; medical_order_id: number | null; order: any; files: typeof files }> = {};
    const orderedKeys: string[] = [];

    files.forEach((f) => {
        const key = f.medical_order_id ? String(f.medical_order_id) : 'unlinked';
        if (!groupsByKey[key]) {
            groupsByKey[key] = {
                key,
                medical_order_id: f.medical_order_id ?? null,
                order: f.medical_order_id ? orderLookup.get(f.medical_order_id) : null,
                files: [],
            };
            orderedKeys.push(key);
        }
        groupsByKey[key].files.push(f);
    });

    return orderedKeys.map((k) => groupsByKey[k]);
});

const toggleVisit = (visitId: number) => {
    if (expandedVisits.value.has(visitId)) {
        expandedVisits.value.delete(visitId);
    } else {
        expandedVisits.value.add(visitId);
    }
};

interface Props {
    patient: {
        id: string;
        user?: { name: string; email: string };
        title?: string;
        name: string;
        surname: string;
        khmer_china_name?: string;
        khmer_china_surname?: string;
        photo_url?: string | null;
        date_of_birth_day: number;
        date_of_birth_month: number;
        date_of_birth_year: number;
        gender: string;
        id_card_or_passport?: string;
        marital_status?: string;
        nationality: string;
        religion?: string;
        race?: string;

        // Address
        address?: string;
        building_village?: string;
        moo?: string;
        soi?: string;
        road?: string;
        sub_district?: string;
        district?: string;
        province?: string;
        zip_code?: string;

        // Contact
        home_phone?: string;
        mobile_phone?: string;
        email?: string;
        occupation?: string;
        company_name?: string;
        company_phone?: string;

        // Emergency Contact
        emergency_contact_name?: string;
        emergency_contact_relationship?: string;
        emergency_contact_description_other?: string;
        emergency_contact_address_same_as_patient?: boolean;
        emergency_contact_address?: string;
        emergency_contact_road?: string;
        emergency_contact_sub_district?: string;
        emergency_contact_district?: string;
        emergency_contact_province?: string;
        emergency_contact_zip_code?: string;
        emergency_contact_home_phone?: string;
        emergency_contact_mobile_phone?: string;
        emergency_contact_email?: string;

        // Payment
        payment_method?: string;
        contract_name?: string;
        insurance_name?: string;
        staff_id?: number;
        patient_type?: string;

        staff?: { id: number; name: string };

        created_at: string;
        updated_at: string;
        patient_files?: Array<any>;
        medical_orders?: Array<any>;
        medical_records?: Array<{
            id: number;
            diagnosis: string;
            treatment: string;
            notes: string;
            date_of_service: string;
            created_at: string;
        }>;
        medical_orders_data?: Array<{
            id: number;
            type: string;
            order_details: string;
            status: string;
            priority: string;
            ordered_at: string;
            completed_at: string | null;
            staff_name: string | null;
            notes: string | null;
        }>;
    };
}

const props = defineProps<Props>();

const { hasPermission } = useAuth();

const createVisit = () => {
    router.visit(`/visits/create?patient=${props.patient.id}`);
};

const sendToNurse = () => {
    // Create visit and send directly to nurse (awaiting assignment status)
    router.post('/visits', {
        patient_id: props.patient.id,
        visit_date_time: new Date().toISOString(),
        status: 'awaiting_assignment',
        notes: 'Quick visit created',
    });
};

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Patients',
        href: '/patients',
    },
    {
        title: 'Details',
        href: '#',
    },
];
</script>

<template>

    <Head title="Patient Details" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div v-if="hasPermission('view_patients')"
            class="flex h-full flex-1 flex-col gap-4 overflow-x-auto rounded-xl p-4">
            <div class="flex items-center gap-4">
                <Button variant="outline" as-child>
                    <a href="/patients">
                        <ArrowLeft class="size-4" />
                        Back
                    </a>
                </Button>
                <div>
                    <h1 class="text-2xl font-bold">
                        {{ patient.title }} {{ patient.name }} {{ patient.surname }}
                    </h1>
                    <p class="text-muted-foreground">
                        View patient information
                    </p>
                </div>
                <div class="ml-auto flex gap-2">
                    <Button variant="outline" as-child>
                        <a :href="`/visits?patient=${props.patient.id}`">
                            <Calendar class="size-4" />
                            View Visit History
                        </a>
                    </Button>
                    <Button as-child>
                        <a :href="`/appointments/create?patient=${props.patient.id}`">
                            <Calendar class="size-4" />
                            Make Appointment
                        </a>
                    </Button>
                    <Button variant="outline" @click="sendToNurse">
                        <Calendar class="size-4" />
                        Quick Visit
                    </Button>

                    <Button variant="outline" as-child>
                        <a :href="`/patients/label?patient=${props.patient.id}`" target="_blank" rel="noopener noreferrer">
                            <Printer class="size-4" />
                            Print Label
                        </a>
                    </Button>
                    <Button variant="outline" as-child>
                        <a :href="`/patients/sticker?patient=${props.patient.id}`" target="_blank" rel="noopener noreferrer">
                            <Printer class="size-4" />
                            Print Sticker
                        </a>
                    </Button>
                    <Button variant="outline" as-child>
                        <a :href="`/patients/report/download?patient=${props.patient.id}`" target="_blank" rel="noopener noreferrer">
                            <Printer class="size-4" />
                            Download Report
                        </a>
                    </Button>
                    <Button variant="outline" as-child>
                        <Link :href="`/patients/edit?patient=${props.patient.id}`">
                            <Edit class="size-4" />
                            Edit
                        </Link>
                    </Button>
                </div>
            </div>

            <!-- Flash error (e.g. duplicate visit) -->
            <div v-if="flashError || formErrors.patient_id"
                class="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-800 dark:bg-red-950/20 dark:text-red-400">
                {{ flashError || formErrors.patient_id }}
            </div>

            <div class="max-w-4xl">
                <Tabs default-value="details" class="w-full">
                    <TabsList class="grid w-full grid-cols-7">
                        <TabsTrigger value="details">Patient Details</TabsTrigger>
                        <TabsTrigger value="files">Files</TabsTrigger>
                        <TabsTrigger value="visit-history">Visit History</TabsTrigger>
                        <TabsTrigger value="medical-orders">Medical Orders</TabsTrigger>
                        <TabsTrigger value="medical-records">Medical Records</TabsTrigger>
                        <TabsTrigger value="medicine-use-report">Medicine Use Report</TabsTrigger>
                        <TabsTrigger value="lab-results">Lab Results</TabsTrigger>
                    </TabsList>
                    <TabsContent value="medicine-use-report" class="mt-6">
                        <div class="flex items-center gap-4 mb-4">
                            <label class="text-sm text-muted-foreground">Date</label>
                            <input type="date" v-model="medicineReportDate" class="border rounded px-2 py-1" />
                            <Button variant="ghost" size="sm" @click="clearMedicineReportDate" v-if="medicineReportDate">
                                Clear
                            </Button>
                        </div>
                        <div v-if="filteredMedicineReport.length === 0" class="rounded-lg border bg-card p-8 text-center">
                            <p class="text-muted-foreground">No medicine usage found for selected date.</p>
                        </div>
                        <div v-else class="overflow-x-auto">
                            <table class="min-w-full divide-y divide-gray-200">
                                <thead>
                                    <tr>
                                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Medicine Name</th>
                                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Dosage</th>
                                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Frequency</th>
                                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Route</th>
                                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="med in filteredMedicineReport" :key="med.id + '-' + med.name + '-' + med.date" class="bg-white">
                                        <td class="px-4 py-2 whitespace-nowrap">{{ med.date }}</td>
                                        <td class="px-4 py-2 whitespace-nowrap">{{ med.name }}</td>
                                        <td class="px-4 py-2 whitespace-nowrap">{{ med.dosage }}</td>
                                        <td class="px-4 py-2 whitespace-nowrap">{{ med.frequency }}</td>
                                        <td class="px-4 py-2 whitespace-nowrap">{{ med.route }}</td>
                                        <td class="px-4 py-2 whitespace-nowrap">{{ med.quantity }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </TabsContent>

                    <TabsContent value="details" class="mt-6 space-y-6">

                        <!-- Personal Information -->
                        <div class="rounded-lg border p-4">
                            <h3 class="mb-4 flex items-center text-lg font-medium">
                                <User class="mr-2 size-5" />
                                Personal Information
                            </h3>
                            <div class="rounded-md border">
                                <table class="w-full">
                                    <tbody>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium w-1/3">Photo</td>
                                            <td class="p-4">
                                                <img
                                                    v-if="patient.photo_url"
                                                    :src="patient.photo_url"
                                                    alt="Patient photo"
                                                    class="h-24 w-24 rounded-md border object-cover"
                                                />
                                                <span v-else class="text-muted-foreground">No photo</span>
                                            </td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium w-1/3">Title</td>
                                            <td class="p-4">{{ patient.title || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">First Name</td>
                                            <td class="p-4">{{ patient.name }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Last Name</td>
                                            <td class="p-4">{{ patient.surname }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Khmer/China Name</td>
                                            <td class="p-4">{{ patient.khmer_china_name || 'N/A' }} {{ patient.khmer_china_surname || '' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Date of Birth</td>
                                            <td class="p-4">{{ patient.date_of_birth_day }}/{{ patient.date_of_birth_month }}/{{ patient.date_of_birth_year }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Gender</td>
                                            <td class="p-4 capitalize">{{ patient.gender }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">ID Card/Passport</td>
                                            <td class="p-4">{{ patient.id_card_or_passport || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Marital Status</td>
                                            <td class="p-4">{{ patient.marital_status || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Nationality</td>
                                            <td class="p-4">{{ patient.nationality }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Religion</td>
                                            <td class="p-4">{{ patient.religion || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Race</td>
                                            <td class="p-4">{{ patient.race || 'N/A' }}</td>
                                        </tr>
                                        <tr v-if="patient.user">
                                            <td class="p-4 font-medium">User Account</td>
                                            <td class="p-4">{{ patient.user.name }} ({{ patient.user.email }})</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <!-- Contact Information -->
                        <div class="rounded-lg border p-4">
                            <h3 class="mb-4 text-lg font-medium">Contact Information</h3>
                            <div class="rounded-md border">
                                <table class="w-full">
                                    <tbody>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium w-1/3">Home Phone</td>
                                            <td class="p-4">{{ patient.home_phone || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Mobile Phone</td>
                                            <td class="p-4">{{ patient.mobile_phone || 'N/A' }}</td>
                                        </tr>
                                        <tr>
                                            <td class="p-4 font-medium">Email</td>
                                            <td class="p-4">{{ patient.email || 'N/A' }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <!-- Address -->
                        <div class="rounded-lg border p-4">
                            <h3 class="mb-4 text-lg font-medium">Address</h3>
                            <div class="rounded-md border">
                                <table class="w-full">
                                    <tbody>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium w-1/3">Address</td>
                                            <td class="p-4">{{ patient.address || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Building/Village</td>
                                            <td class="p-4">{{ patient.building_village || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Moo</td>
                                            <td class="p-4">{{ patient.moo || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Soi</td>
                                            <td class="p-4">{{ patient.soi || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Road</td>
                                            <td class="p-4">{{ patient.road || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Sub-district</td>
                                            <td class="p-4">{{ patient.sub_district || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">District</td>
                                            <td class="p-4">{{ patient.district || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Province</td>
                                            <td class="p-4">{{ patient.province || 'N/A' }}</td>
                                        </tr>
                                        <tr>
                                            <td class="p-4 font-medium">Zip Code</td>
                                            <td class="p-4">{{ patient.zip_code || 'N/A' }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <!-- Employment -->
                        <div class="rounded-lg border p-4">
                            <h3 class="mb-4 text-lg font-medium">Employment</h3>
                            <div class="rounded-md border">
                                <table class="w-full">
                                    <tbody>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium w-1/3">Occupation</td>
                                            <td class="p-4">{{ patient.occupation || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Company Name</td>
                                            <td class="p-4">{{ patient.company_name || 'N/A' }}</td>
                                        </tr>
                                        <tr>
                                            <td class="p-4 font-medium">Company Phone</td>
                                            <td class="p-4">{{ patient.company_phone || 'N/A' }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <!-- Emergency Contact -->
                        <div class="rounded-lg border p-4">
                            <h3 class="mb-4 text-lg font-medium">Emergency Contact</h3>
                            <div class="rounded-md border">
                                <table class="w-full">
                                    <tbody>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium w-1/3">Name</td>
                                            <td class="p-4">{{ patient.emergency_contact_name || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Relationship</td>
                                            <td class="p-4">{{ patient.emergency_contact_relationship || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Other Relationship</td>
                                            <td class="p-4">{{ patient.emergency_contact_description_other || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Same as Patient Address</td>
                                            <td class="p-4">{{ patient.emergency_contact_address_same_as_patient ? 'Yes' : 'No' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Address</td>
                                            <td class="p-4">{{ patient.emergency_contact_address || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Road</td>
                                            <td class="p-4">{{ patient.emergency_contact_road || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Sub-district</td>
                                            <td class="p-4">{{ patient.emergency_contact_sub_district || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">District</td>
                                            <td class="p-4">{{ patient.emergency_contact_district || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Province</td>
                                            <td class="p-4">{{ patient.emergency_contact_province || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Zip Code</td>
                                            <td class="p-4">{{ patient.emergency_contact_zip_code || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Home Phone</td>
                                            <td class="p-4">{{ patient.emergency_contact_home_phone || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Mobile Phone</td>
                                            <td class="p-4">{{ patient.emergency_contact_mobile_phone || 'N/A' }}</td>
                                        </tr>
                                        <tr>
                                            <td class="p-4 font-medium">Email</td>
                                            <td class="p-4">{{ patient.emergency_contact_email || 'N/A' }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <!-- Insurance & Payment -->
                        <div class="rounded-lg border p-4">
                            <h3 class="mb-4 text-lg font-medium">Insurance & Payment</h3>
                            <div class="rounded-md border">
                                <table class="w-full">
                                    <tbody>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium w-1/3">Payment Method</td>
                                            <td class="p-4 capitalize">{{ patient.payment_method || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Contract Name</td>
                                            <td class="p-4">{{ patient.contract_name || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Insurance Name</td>
                                            <td class="p-4">{{ patient.insurance_name || 'N/A' }}</td>
                                        </tr>
                                        <tr class="border-b">
                                            <td class="p-4 font-medium">Referring Doctor</td>
                                            <td class="p-4">{{ patient.staff?.name || 'N/A' }}</td>
                                        </tr>
                                        <tr>
                                            <td class="p-4 font-medium">Patient Type</td>
                                            <td class="p-4">{{ patient.patient_type || 'N/A' }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </TabsContent>

                    <TabsContent value="files" class="mt-6">
                        <PatientFilesTab :patient="props.patient" />
                    </TabsContent>

                    <TabsContent value="visit-history" class="mt-6">
                        <div class="flex items-center gap-4 mb-4">
                            <label class="text-sm text-muted-foreground">Date</label>
                            <input type="date" v-model="visitHistoryDate" class="border rounded px-2 py-1" />
                            <Button variant="ghost" size="sm" @click="clearVisitHistoryDate" v-if="visitHistoryDate">
                                Clear
                            </Button>
                        </div>
                        <div v-if="filteredVisitHistory.length === 0" class="rounded-lg border bg-card p-8 text-center">
                            <p class="text-muted-foreground">No visit history found for selected date.</p>
                        </div>
                        <div v-else class="space-y-2">
                            <div v-for="visit in filteredVisitHistory" :key="visit.id" class="rounded-lg border bg-card overflow-hidden">
                                <button
                                    class="flex w-full items-center gap-4 p-4 text-left hover:bg-muted/50 transition-colors"
                                    @click="toggleVisit(visit.id)"
                                >
                                    <ChevronRight
                                        class="h-4 w-4 shrink-0 text-muted-foreground transition-transform duration-200"
                                        :class="{ 'rotate-90': expandedVisits.has(visit.id) }"
                                    />
                                    <div class="flex flex-1 items-center gap-4 min-w-0">
                                        <span class="text-sm font-medium whitespace-nowrap">
                                            {{ formatDateTime(visit.visit_date_time) }}
                                        </span>
                                        <span v-if="visit.staff_name" class="text-sm text-muted-foreground truncate">
                                            {{ visit.staff_name }}
                                        </span>
                                    </div>
                                    <Badge
                                        :variant="visit.status === 'completed' ? 'default' : visit.status === 'processing' ? 'secondary' : 'outline'"
                                        class="shrink-0"
                                    >
                                        {{ visit.status }}
                                    </Badge>
                                </button>
                                <div v-if="expandedVisits.has(visit.id)" class="border-t px-6 pb-6 pt-4">
                                    <div class="grid gap-4 md:grid-cols-2">
                                        <div v-if="visit.priority" class="space-y-2">
                                            <dt class="text-sm font-medium text-muted-foreground">
                                                Priority
                                            </dt>
                                            <dd class="text-sm">
                                                <Badge variant="destructive" v-if="visit.priority === 'stat'">
                                                    {{ visit.priority }}
                                                </Badge>
                                                <Badge variant="secondary" v-else>
                                                    {{ visit.priority }}
                                                </Badge>
                                            </dd>
                                        </div>
                                    </div>

                                    <!-- Medical Orders Section -->
                                    <div v-if="visit.medical_orders && visit.medical_orders.length > 0" class="mt-6 space-y-4">
                                        <h4 class="text-sm font-semibold">Medical Orders</h4>
                                        <div v-for="order in visit.medical_orders" :key="order.id" class="space-y-3 rounded-md border bg-muted/30 p-4">
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium">Order #{{ order.id }}</span>
                                                <Badge :variant="order.status.value === 'completed' ? 'default' : 'secondary'">
                                                    {{ order.status.label }}
                                                </Badge>
                                            </div>

                                            <div v-if="order.order_details" class="text-sm text-muted-foreground">
                                                {{ order.order_details }}
                                            </div>

                                            <!-- Order Items -->
                                            <div v-if="order.items && order.items.length > 0" class="space-y-2">
                                                <div v-for="(item, idx) in order.items" :key="idx" class="flex items-start justify-between rounded border bg-background p-3">
                                                    <div class="flex-1">
                                                        <p class="text-sm font-medium">{{ item.item_name }}</p>
                                                        <p class="text-xs text-muted-foreground">
                                                            Type: {{ item.item_type }} | Qty: {{ item.quantity }}
                                                        </p>
                                                        <p v-if="item.details" class="text-xs text-muted-foreground mt-1">
                                                            {{ item.details }}
                                                        </p>
                                                        <p v-if="item.notes" class="text-xs text-muted-foreground mt-1 italic">
                                                            Note: {{ item.notes }}
                                                        </p>
                                                    </div>
                                                    <div class="ml-4 text-right">
                                                        <Badge :variant="item.status.value === 'completed' ? 'default' : 'secondary'" class="mb-2">
                                                            {{ item.status.label }}
                                                        </Badge>
                                                        <p class="text-sm font-medium text-green-600 dark:text-green-400">
                                                            ${{ (item.selling_price * item.quantity).toFixed(2) }}
                                                        </p>
                                                        <p v-if="item.selling_price === 0" class="text-xs text-muted-foreground">
                                                            (Package)
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Billing Section -->
                                    <div v-if="visit.billings && visit.billings.length > 0" class="mt-6 space-y-3">
                                        <h4 class="text-sm font-semibold">Billing Information</h4>
                                        <div v-for="billing in visit.billings" :key="billing.id" class="rounded-md border bg-muted/30 p-4">
                                            <div class="grid gap-3 md:grid-cols-3">
                                                <div>
                                                    <dt class="text-xs font-medium text-muted-foreground">Total Amount</dt>
                                                    <dd class="text-sm font-semibold">${{ billing.total_amount }}</dd>
                                                </div>
                                                <div>
                                                    <dt class="text-xs font-medium text-muted-foreground">Paid Amount</dt>
                                                    <dd class="text-sm font-semibold text-green-600">${{ billing.paid_amount }}</dd>
                                                </div>
                                                <div>
                                                    <dt class="text-xs font-medium text-muted-foreground">Payment Status</dt>
                                                    <dd>
                                                        <Badge :variant="billing.payment_status === 'paid' ? 'default' : billing.payment_status === 'partial' ? 'secondary' : 'destructive'">
                                                            {{ billing.payment_status }}
                                                        </Badge>
                                                    </dd>
                                                </div>
                                                <div v-if="billing.payment_method">
                                                    <dt class="text-xs font-medium text-muted-foreground">Payment Method</dt>
                                                    <dd class="text-sm">{{ billing.payment_method }}</dd>
                                                </div>
                                                <div>
                                                    <dt class="text-xs font-medium text-muted-foreground">Billing Date</dt>
                                                    <dd class="text-sm">{{ formatDate(billing.billing_date) }}</dd>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Notes -->
                                    <div v-if="visit.notes" class="mt-4 space-y-2">
                                        <dt class="text-sm font-medium text-muted-foreground">Notes</dt>
                                        <dd class="text-sm whitespace-pre-line rounded-md bg-muted/50 p-3">
                                            {{ visit.notes }}
                                        </dd>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </TabsContent>

                    <TabsContent value="medical-records" class="mt-6">
                        <div class="space-y-4">
                            <div class="flex items-center justify-between">
                                <div>
                                    <h3 class="text-lg font-semibold">Medical Records</h3>
                                    <p class="text-sm text-muted-foreground">
                                        Complete medical history and treatment records
                                    </p>
                                </div>
                            </div>

                            <div v-if="!props.patient.medical_records || props.patient.medical_records.length === 0"
                                class="rounded-lg border bg-card p-8 text-center">
                                <p class="text-muted-foreground">No medical records found.</p>
                            </div>

                            <div v-else class="space-y-4">
                                <div v-for="record in props.patient.medical_records" :key="record.id"
                                    class="rounded-lg border bg-card p-6">
                                    <div class="grid gap-4 md:grid-cols-2">
                                        <div class="space-y-2">
                                            <dt class="text-sm font-medium text-muted-foreground">
                                                Date of Service
                                            </dt>
                                            <dd class="text-sm">
                                                {{ formatDate(record.date_of_service) }}
                                            </dd>
                                        </div>

                                        <div class="space-y-2">
                                            <dt class="text-sm font-medium text-muted-foreground">
                                                Record ID
                                            </dt>
                                            <dd class="text-sm font-mono">
                                                #{{ record.id }}
                                            </dd>
                                        </div>
                                    </div>

                                    <div class="mt-4 space-y-4">
                                        <div v-if="record.diagnosis" class="space-y-2">
                                            <dt class="text-sm font-medium text-muted-foreground">
                                                Diagnosis
                                            </dt>
                                            <dd class="text-sm whitespace-pre-line">
                                                {{ record.diagnosis }}
                                            </dd>
                                        </div>

                                        <div v-if="record.treatment" class="space-y-2">
                                            <dt class="text-sm font-medium text-muted-foreground">
                                                Treatment
                                            </dt>
                                            <dd class="text-sm whitespace-pre-line">
                                                {{ record.treatment }}
                                            </dd>
                                        </div>

                                        <div v-if="record.notes" class="space-y-2">
                                            <dt class="text-sm font-medium text-muted-foreground">
                                                Notes
                                            </dt>
                                            <dd class="text-sm whitespace-pre-line">
                                                {{ record.notes }}
                                            </dd>
                                        </div>
                                    </div>

                                    <div class="mt-4 pt-4 border-t">
                                        <p class="text-xs text-muted-foreground">
                                            Created: {{ formatDateTime(record.created_at) }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </TabsContent>

                    <!-- Lab Results Tab -->
                    <TabsContent value="lab-results" class="mt-6">
                        <div v-if="labResultGroups.length === 0" class="rounded-lg border bg-muted/50 p-10 text-center">
                            <FlaskConical class="mx-auto mb-3 h-10 w-10 opacity-40" />
                            <p class="text-sm text-muted-foreground">No lab results recorded yet.</p>
                        </div>
                        <div v-else class="space-y-4">
                            <template v-for="group in labResultGroups" :key="group.key">
                                <details class="group rounded-lg border bg-card">
                                    <summary class="flex cursor-pointer items-center justify-between gap-4 px-4 py-4 transition-colors hover:bg-muted/50">
                                        <div class="min-w-0">
                                            <p class="font-semibold text-sm text-blue-700 dark:text-blue-300">
                                                <a v-if="group.medical_order_id" :href="`/medical-orders/${group.medical_order_id}`" class="hover:underline">
                                                    Lab Order #{{ group.medical_order_id }}
                                                </a>
                                                <span v-else>Unlinked Lab Files</span>
                                            </p>
                                            <p class="text-xs text-muted-foreground">
                                                {{ (group.order?.ordered_at || group.files[0]?.created_at)?.slice(0, 10) || 'No date' }}
                                                <template v-if="group.order?.staff_name"> &middot; Dr. {{ group.order.staff_name }}</template>
                                            </p>
                                        </div>
                                        <span class="text-xs text-muted-foreground">Click to expand</span>
                                    </summary>

                                    <div class="divide-y border-t px-4 pb-4">
                                        <div v-for="item in group.files" :key="item.id" class="flex items-center justify-between gap-4 px-0 py-4">
                                            <div class="min-w-0">
                                                <p class="font-medium text-sm">{{ item.file.name }}</p>
                                                <p class="text-xs text-muted-foreground">{{ formatDateTime(item.created_at) }}</p>
                                            </div>
                                            <div class="flex shrink-0 gap-2">
                                                <Button variant="outline" size="sm" as-child>
                                                    <a :href="`${showPatientFile(item.id).url}?inline=1`" target="_blank">
                                                        <Eye class="size-4" />
                                                    </a>
                                                </Button>
                                                <Button variant="outline" size="sm" as-child>
                                                    <a :href="showPatientFile(item.id).url" target="_blank">
                                                        <Download class="size-4" />
                                                    </a>
                                                </Button>
                                            </div>
                                        </div>
                                    </div>
                                </details>
                            </template>
                        </div>
                    </TabsContent>
                </Tabs>
            </div>
        </div>
        <div v-else class="flex h-full flex-1 flex-col items-center justify-center gap-4 rounded-xl p-4">
            <div class="text-center">
                <h2 class="text-2xl font-bold text-destructive">Access Denied</h2>
                <p class="text-muted-foreground">
                    You don't have permission to view patient details.
                </p>
            </div>
        </div>
    </AppLayout>
</template>
